name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  create-branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.create-branch.outputs.branch }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create new branch
        id: create-branch
        run: |
          BRANCH_NAME="extracto/nome-${{ github.run_id }}"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
          echo "::set-output name=branch::$BRANCH_NAME"

  create-pr:
    runs-on: ubuntu-latest
    needs: create-branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.create-branch.outputs.branch }}

      # - name: Run custom action to create PR
      #   uses: ./actions/create-pr
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ needs.create-branch.outputs.branch }}
      #     base: 'main'
      #     commit_message: 'Adiciona novo pacote e atualiza dependências'
      #     title: 'Adiciona novo pacote e atualiza dependências'
      #     body: 'Este PR adiciona um novo pacote e atualiza as dependências.'
      - name: Create Pull Request
        uses: juliobsilva/action-github-create-pullrequest@main
        with:
          token:           ${{ secrets.GITHUB_TOKEN }}
          branch:          ${{ needs.create-branch.outputs.branch }}
          base:            "main"
          commit_message: "A Message for your commit"
          title:          "A title for your pull_request" 
          body:           "A Message for your pull_request"